### ISSUE TITLE
Only seen as switch, supports "on/off" through Google Home

### ISSUE THREAD

**Issue by CLHatch** [dcmeglio/hubitat-bond#10]
Using the "Bond Fan Light" driver, when I link the ceiling fan from the Hubitat to Google Home, it only shows as a switch to Google Home, and gives no way of controlling the fan speed.  When linking directly from Bond to Google Home, it allows the speed change, as expected.

**Comment by dcmeglio** [comment]
This is a limitation of the Hubitat Google Home. Unfortunately there is nothing I can do about it. You’d need to convince Hubitat to add this support.
