### ISSUE TITLE
Is it possible to add a position value?

### ISSUE THREAD

**Issue by dcc530** [dcmeglio/hubitat-bond#15]
It only shows "switch" and "windowShade" at the moment. 
Is it possible to add a "position" value? It can be 0 (closed), 50 (halfway) and 100 (open).
Without this value, I can't use the Hubitat plugin that will allow me to ask Google Assistant to change the blind position.
Thanks.
<img width="1002" alt="Screen Shot 2021-01-27 at 12 17 58 pm" src="https://user-images.githubusercontent.com/2841294/105929051-e188c880-609a-11eb-8a39-533cc39aa783.png">

**Comment by dcmeglio** [comment]
Are ytou using the version released this week? This feature was already added.

**Comment by dcc530** [comment]
Yeah, I'm using the latest version. The latest feature "setPosition" works great!
However, how can I get the current position value? I can see there are currently only two capabilities "WindowShade" and "Switch" in the source code. 
Is it possible to include the position value?

![aaa](https://user-images.githubusercontent.com/2841294/105944307-29b5e400-60b7-11eb-8b28-7a95acfc1388.png)

**Comment by dcc530** [comment]
Just made a quick change in the code. The blinds are now working perfectly with Google Assistant.
