### ISSUE TITLE
How do I issue the stop command in Rule Machine?

### ISSUE THREAD

**Issue by simondsmason** [dcmeglio/hubitat-bond#26]
I can't figure out how to access in the STOP command in Rule Machine?  I searched the forums but didn't see anything about this.  Any help would be appreciated.  Thanks.

**Comment by PretzelBane** [comment]
What do you want to STOP?
If it is the current rule that is running, then I think you want EXIT RULE.  It' all the way at the bottom of the picklist under "Delay, Wait, Exit or Comment".  This will end the rule at wherever it is at and any subsequent Actions will not occur.  Of course, anything before the Exit command will have already executed and will still happen - even if it had a delay on it.

**Comment by simondsmason** [comment]
Sorry, should have been clearer.  My blinds respond to OPEN, CLOSE, and STOP.  If you issue a STOP while they are moving then they stop moving.  It you issue a STOP when they are not moving they go to the preset position.  This works with the original remotes, and also in the Bond app.  

When I use the Stop button in the device screen in Hubitat it works.  In the Rule engine I see an option for open/close which works fine.  I then see an option for Stop Shades.  When I use this it does not work.  It does not stop the blinds when they are moving and it does not move the blinds to the preset position when issued when they are not moving.

Hopefully that is clearer?  Happy to provide logs or other information as is relevant?  Thanks.

**Comment by PretzelBane** [comment]
I guess I can’t help much with that.  I don’t have any shades.  If I look at a virtual shade it only has commands for open, close, on, and off.  No stop.  There are, however, parameters to set the start and stop position values.  Maybe your device is like that too and you need to stop by setting a parameter rather than issuing a command.  You can try the Run Custom Action command to do that.  Just a thought.

**Comment by simondsmason** [comment]
Bingo - it was in the custom actions.  I thought I tried that but apparently not.  Thanks for the pointer.

**Comment by simondsmason** [comment]
Problem solved.
