### ISSUE TITLE
Driver for Fan with multiple options

### ISSUE THREAD

**Issue by mydevbox** [dcmeglio/hubitat-bond#4]
Thanks for putting this integration together.

One of my ceiling fans has the following options. Is there a way to add driver(s) to support all of these at the same time?

- Dimmable light
- Timer
- 6 Speeds
- Multi-direction

**Comment by matt1097** [comment]
I was going to post a similar issue.
If i select the fan with direction driver, the child light device does not let me change driver and does not have the dimmable option, only on/off. The child is locked to bond fan light driver

**Comment by dcmeglio** [comment]
Never heard back
