### ISSUE TITLE
Not picking up all fans

### ISSUE THREAD

**Issue by samcayford** [dcmeglio/hubitat-bond#8]
Thanks for the app, having one issue....

My bond has 4 fans set up but the drop down to select fans in the app only lists 2 of them. Any idea how i go about finding out why the others are not listed?

Thanks

**Comment by samcayford** [comment]
Aha, never mind. I re-added them to bond and they showed up. I wonder if it could have been something to do with them being added in the old bond app or something?

**Comment by apwelsh** [comment]
I had this same issue. My new fan was linked to bond via my phone but not via the cloud. I had to delete it, and then select the bond and add the fan there. Kind of weird.

**Comment by dcmeglio** [comment]
Yeah, this actually makes sense. When Bond first came out certain fans were added as "cloud devices" and the API can't see them. Over time they find a way to make all of the devices "local" so they'd work with the API. So if you added a device a long time ago it's possible it's a cloud device. Deleting and readding makes it local. So it's confusing, but it makes sense
